### PR TITLE
Fix (js): Fix Bubble.getPeekIndices() to return desired indices for singleline and multiline truth value

### LINKED ISSUE #11: Trainer speech showing too many lines when book text < 100 characters
## Bug

Trainer speech showing too many lines when book text < 100 characters

## Expectation

Trainer speech not showing too many lines when book text < 100 characters

## Discussion

Only happens when there are many newlines in the book with text < 100 characters.

This can be a problem because the student response is too far down to see the trainer speech.

### PR DESCRIPTION
**Pull request by leojonathanoh**
Fixes #11

### CODE REVIEW

File: assets/js/app.js [hunk 1]
```diff
@@ -313,57 +313,119 @@ var Bubble = function(default_value) {
...
-            // From this point, determine if the truth value is multiline.
-            // Determine all LF indices of truth value. Consider the start of string as a LF
-            var lfIndices = [0];
-            if (lfIndices.length > 0) {
-                for (var i = 0; i < truth.value.length; i++) {
-                    if (/\n/.test(truth.value[i])) {
-                        lfIndices.push(i);
-                    }
-                }
+        // return truth.value.substr(startIndex, endIndex - startIndex);
```
Comment (leojonathanoh) [inline assets/js/app.js]: remove this

**Review by leojonathanoh — COMMENTED** [review]
lgtm
